name: youtube_music_clone
description: Messenger of the gods

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  flutter_vector_icons:
  cached_network_image:
  intl:
  flutter_bloc: ^3.2.0
  bloc: ^3.0.0
  equatable:
  dio: ^3.0.10
  shared_preferences:
  path:
  page_view_indicators:
  flutter_svg: ^0.18.0
  provider:
  kiwi: ^0.2.0
  http:
  dartz: ^0.8.9
  json_serializable:
  url_launcher: ^5.4.2
  video_thumbnail: ^0.2.0
  pin_code_fields: ^2.3.0+3
  sqlcool: ^4.3.1
  flutter_sim_country_code: ^0.0.3
  geolocator: ^5.3.0
  permission_handler: ^4.2.0+hotfix.3
  image_picker: ^0.6.3+4
  inview_notifier_list: ^0.0.4
  flutter_launcher_icons: ^0.7.4
  flutter_cache_manager: ^1.1.3
  rating_bar:
  lottie: ^0.2.2
  timeago: ^2.0.26
  pull_to_refresh: ^1.5.8
  flutter_platform_widgets: ^0.32.4
  android_intent: any
  dynamic_theme: 1.0.1
  barcode_scan: any
  toast: ^0.1.5
  moor_flutter: 
  rflutter_alert: ^1.0.3
  shimmer: ^1.1.1
  pin_entry_text_field: ^0.1.4
  modal_progress_hud:
  printing: ^3.7.1
  share:
    git:
      url: git://github.com/himanshusharma89/plugins.git
      path: packages/share
  path_provider: ^1.6.11
  flutter_rating_bar: ^3.0.1+1
 
  




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: 
  build_runner:
  kiwi_generator: ^0.4.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
   # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NoirPro
      fonts:
        - asset: assets/fonts/NoirPro-Bold.otf
        - asset: assets/fonts/NoirPro-Medium.otf
        - asset: assets/fonts/NoirPro-Regular.otf
          style: normal

        
         

  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
